[project]
name = "sheet-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bittensor>=9.12.2",
    "bittensor-cli>=9.15.3",
    "fastapi[standard]>=0.110.3",
]
